services:
  medical-clinic:
    build: .
    ports:
      - "8080:2137"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:clinicdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_SHOW_SQL=true
    restart: unless-stopped